version: "3.8"

services:
  team_estimator:
    build: .
    container_name: team_estimator_cli
    tty: true
    stdin_open: true
    volumes:
      # Mount SSH Keys as readonly
      - ~/.ssh:/root/.ssh:ro
      # Mount gitconfig
      - ~/.gitconfig:/root/.gitconfig:ro
      # Mount working folder
      - ./:/home/workspace
